web:
  build: .
  dockerfile: Dockerfile-development
  links:
   - db
  ports:
   - "3000:3000"
  volumes:
   - .:/usr/src/app/
  environment:
   PORT: 3000,
   NODE_ENV: development,
   MONGO_URL: mongodb://db:27017/logistic-system-dolce
db:
  image: mongo:latest
  ports:
   - "27017:27017"
