
version: '2'

services:
  logistic-system-dolce:
    image: logistic-system-dolce:latest
    build:
      context: .
      dockerfile: Dockerfile
    links: 
      - db
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db:27017/logistic-system-dolce
    ports:
      - 8000:8000
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 ./src/server/index.js
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
