FROM node
MAINTAINER Mateo Quintero <quinterom1592@gmail.com>

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app
RUN npm install
# Bundle app source
COPY . /usr/src/app

ENV NODE_ENV development

EXPOSE 3000
CMD ["npm", "run", "dev"]
