/**
 * Module with the app actions.
 * @module src/shared/constants/actions
 */
// App.
export const LOCATION_CHANGE = 'LOCATION_CHANGE';
export const INIT_ADMIN_STATE = 'INIT_STATE';

// Loading.
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

// Toast List.
export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

// Form Rules.
export const UPDATE_RULES_VALIDATION = 'UPDATE_RULES_VALIDATION';
export const CLEAR_RULES_VALIDATION = 'CLEAR_RULES_VALIDATION';

// Data Table.
export const UPDATE_SERIALIZED_DATA_TABLE = 'UPDATE_SERIALIZED_DATA_TABLE';
export const UPDATE_SELECTED_DATA_TABLE = 'UPDATE_SELECTED_DATA_TABLE';
export const CLEAR_SERIALIZED_DATA_TABLE = 'CLEAR_SERIALIZED_DATA_TABLE';

// User.
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Login Form.
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const TOGGLE_REMEMBERME = 'TOGGLE_REMEMBERME';

// Users.
export const UPDATE_NEW_USER_FORM = 'UPDATE_NEW_USER_FORM';
export const ADD_NEW_USER_REQUEST = 'ADD_NEW_USER_REQUEST';
export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';
export const ADD_NEW_USER_FAILED = 'ADD_NEW_USER_FAILED';
export const SELECT_USER_TO_EDIT = 'SELECT_USER_TO_EDIT';
export const CLEAR_USER_TO_EDIT = 'CLEAR_USER_TO_EDIT';

export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST';
export const UPDATE_USERS_FILTER = 'UPDATE_USERS_FILTER';
export const CLEAR_USERS_FILTER = 'CLEAR_USERS_FILTER';

export const UPDATE_USER_TYPES = 'UPDATE_USER_TYPES';

// Transporters.
export const INIT_TRANSPORTER_LIST = 'INIT_TRANSPORTER_LIST';
export const UPDATE_TRANSPORTER_LIST = 'UPDATE_TRANSPORTER_LIST';

export const UPDATE_TRANSPORTER_FORM_USER = 'UPDATE_TRANSPORTER_FORM_USER';
export const UPDATE_TRANSPORTER_FORM_MASTER = 'UPDATE_TRANSPORTER_FORM_MASTER';
export const ASSIGN_TRANSPORTER_REQUEST = 'ASSIGN_TRANSPORTER_REQUEST';
export const ASSIGN_TRANSPORTER_SUCCESS = 'ASSIGN_TRANSPORTER_SUCCESS';
export const ASSIGN_TRANSPORTER_FAILED = 'ASSIGN_TRANSPORTER_FAILED';

export const UPDATE_DISTRIBUTOR_FORM_LIST = 'UPDATE_DISTRIBUTOR_FORM_LIST';
export const UPDATE_DISTRIBUTOR_FORM_TRANSPORTER = 'UPDATE_DISTRIBUTOR_FORM_TRANSPORTER';
export const UPDATE_DISTRIBUTOR_FORM_DISTRIBUTORS = 'UPDATE_DISTRIBUTOR_FORM_DISTRIBUTORS';
export const ASSIGN_DISTRIBUTOR_REQUEST = 'ASSIGN_DISTRIBUTOR_REQUEST';
export const ASSIGN_DISTRIBUTOR_SUCCESS = 'ASSIGN_DISTRIBUTOR_SUCCESS';
export const ASSIGN_DISTRIBUTOR_FAILED = 'ASSIGN_DISTRIBUTOR_FAILED';

// Transporters Filter.
export const UPDATE_TRANSPORTERS_FILTER = 'UPDATE_TRANSPORTERS_FILTER';

// Dashboard.
export const UPDATE_MAIN_GROUP_SELECTION = 'UPDATE_MAIN_GROUP_SELECTION';
export const UPDATE_ZONE_SELECTION = 'UPDATE_ZONE_SELECTION';

// Package Reception.
export const UPDATE_ORDER_LIST = 'UPDATE_ORDER_LIST';
export const UPDATE_ORDERS_FORM = 'UPDATE_ORDERS_FORM';
export const UPDATE_ORDERS_OBSERVATION = 'UPDATE_ORDERS_OBSERVATION';
export const TOGGLE_ALL_ORDERS = 'TOGGLE_ALL_ORDERS';
export const TOGGLE_ORDER = 'TOGGLE_ORDER';

export const PACKAGE_RECEPTION_REQUEST = 'PACKAGE_RECEPTION_REQUEST';
export const PACKAGE_RECEPTION_SUCCESS = 'PACKAGE_RECEPTION_SUCCESS';
export const PACKAGE_RECEPTION_FAILED = 'PACKAGE_RECEPTION_FAILED';
