/**
 * Module with the app actions.
 * @module src/shared/constants/actions
 */
// App.
export const LOCATION_CHANGE = 'LOCATION_CHANGE';
export const INIT_ADMIN_STATE = 'INIT_STATE';

// Loading.
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

// Toast List.
export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

// Form Rules.
export const UPDATE_RULES_VALIDATION = 'UPDATE_RULES_VALIDATION';
export const CLEAR_RULES_VALIDATION = 'CLEAR_RULES_VALIDATION';

// User.
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Login Form.
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const TOGGLE_REMEMBERME = 'TOGGLE_REMEMBERME';

// Users.
export const UPDATE_NEW_USER_FORM = 'UPDATE_NEW_USER_FORM';
export const ADD_NEW_USER_REQUEST = 'ADD_NEW_USER_REQUEST';
export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';
export const ADD_NEW_USER_FAILED = 'ADD_NEW_USER_FAILED';
export const SELECT_USER_TO_EDIT = 'SELECT_USER_TO_EDIT';
export const CLEAR_USER_TO_EDIT = 'CLEAR_USER_TO_EDIT';

export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST';
export const UPDATE_USERS_FILTER = 'UPDATE_USERS_FILTER';
export const CLEAR_USERS_FILTER = 'CLEAR_USERS_FILTER';

export const UPDATE_USER_TYPES = 'UPDATE_USER_TYPES';

// Dashboard.
export const UPDATE_MAIN_GROUP_SELECTION = 'UPDATE_MAIN_GROUP_SELECTION';
export const UPDATE_ZONE_SELECTION = 'UPDATE_ZONE_SELECTION';

// Package Reception.
export const UPDATE_CAMPAIGNS = 'UPDATE_CAMPAIGNS';
export const SELECT_CAMPAIGN = 'SELECT_CAMPAIGN';
export const TOGGLE_SELECT_ALL = 'TOGGLE_SELECT_ALL';
export const TOGGLE_ORDER = 'TOGGLE_ORDER';
